#
# Makefile for the i2c core.
#

#regdebug-objs := regdebug.o ../media/video/mxc/capture/sensor_clock.o
obj-$(CONFIG_REG_DEBUG)	+= regdebug.o

obj-$(CONFIG_PIC_18F)	+= pic18f.o

obj-$(CONFIG_STIM_PM)	+= stim_pm.o